### ISSUE TITLE
Special character selection doesn't yet work

### ISSUE THREAD

**Issue by Pakue95** [comakingspace/FlipDotDisplay#1]
https://github.com/comakingspace/FlipDotDisplay/blob/ac73b9dc514dd0b5a6fa421b96d9adefe22393e7/Code/FDD-Common_Room/FDD-Common_Room.ino#L193

When I tired the code yesterday I got the same results as before with weird characters being displayed in place of äö etc.

**Comment by NitramLegov** [comment]
https://github.com/comakingspace/FlipDotDisplay/commit/ef07109a65e885bc6020e12cc33ae8bb8f182b74 fixed this
