### ISSUE TITLE
Byte stream via MQTT causes crash 

### ISSUE THREAD

**Issue by Pakue95** [comakingspace/FlipDotDisplay#2]
https://github.com/comakingspace/FlipDotDisplay/blob/ac73b9dc514dd0b5a6fa421b96d9adefe22393e7/Code/FDD-Common_Room/FDD-Common_Room.ino#L164-167

when leaving these three lines in the code the ESP crashes upon sending MQTT messages on either "Text" or "Binary" topics, suggesting the conditional `subscription == &binaryTopic` returns as true during every call of the MQTT function.

**Comment by NitramLegov** [comment]
Weird.
I´ll try to convert the current logic into a callback-based logic based on the following example:
https://github.com/adafruit/Adafruit_MQTT_Library/tree/master/examples/mqtt_esp8266_callback

Hopefully this resolves the issue in here.

**Comment by Pakue95** [comment]
237c0ffd23c448714550f401af9276b747ea4fe5 should have fixed the crashes by using the Callback function. The code is however still a mess and MQTT doesn't like sending more than ~100 bytes. I opened a new issue #3 for this problem.
